name: Publish Package

on:
  push:
    branches: [ master ]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v') && github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
      - run: git config --global user.name "Github Actions"
      - run: git config --global user.email "actions@users.noreply.github.com"
      - run: npm install ts-dev-stack node-version-use depcheck @biomejs/biome@2.2.6 mocha -g -f
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: npm publish